backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Log Entries"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
